//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDisk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTable
    {
        public int SalesInvoiceId { get; set; }
        public string SalesInvoiceNumber { get; set; }
        public string SalesRefNumber { get; set; }
        public Nullable<System.DateTime> ISalesnvoiceDate { get; set; }
        public string SalesDueDate { get; set; }
        public Nullable<int> SalesPayementTerm { get; set; }
        public Nullable<double> SalesSubtotal { get; set; }
        public Nullable<double> SalesDiscount { get; set; }
        public Nullable<double> SalesDiscountAmount { get; set; }
        public Nullable<double> SalesTotalAmount { get; set; }
        public string SalesCustomerNote { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
