//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDisk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetailsTable
    {
        public int? SalesDetailsId { get; set; }
        public Nullable<int> SalesItemId { get; set; }
        public string SalesDescription { get; set; }
        public Nullable<int> SalesQunatity { get; set; }
        public Nullable<double> SalesItemRate { get; set; }
        public Nullable<double> SalesTotal { get; set; }
        public Nullable<double> SalesVat { get; set; }
        public Nullable<int> SalesInvoiceId { get; set; }
    }
}
