//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDisk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatDetailsTable
    {
        public int VatID { get; set; }
        public Nullable<double> VatPercentage { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> QutationId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
